#!/bin/bash
cd fast-downward/src/
date1=$(date +%s%N | cut -b1-13)
searchtime=0
trace="$1"
domain="Conformance_Checking/domain$trace.pddl"
problem="Conformance_Checking/problem$trace.pddl"
translate/translate.py $domain $problem < output.sas
preprocess/preprocess < output.sas
prima=$(date +%s%N | cut -b1-13)
./search/downward --heuristic "hff=ff()"  --heuristic "hcea=cea()" --search "astar(blind())" < output
dopo=$(date +%s%N | cut -b1-13)
searchtime=$(($searchtime+$dopo-$prima))
date2=$(date +%s%N | cut -b1-13)
diff=$(($date2-$date1))
transtime=$(($diff-$searchtime))
#echo $date1
#echo $date2
echo "the duration for trace #$trace is: $diff ms."
echo "the search time is: $searchtime ms."
echo "the translation time is: $transtime ms."
