#!/bin/bash
cd seq-opt-symba-2
date1=$(date +%s%N | cut -b1-13)
searchtime=0
traces=0
for f in Conformance_Checking/domain*.pddl
do
traces=$(($traces+1))
basename=$(basename -- "$f")
filename="${basename%.*}"
trace=$(echo $filename| cut -d'n' -f 2)
f2="${f/domain/problem}"
out=results/out_"$trace".txt
echo $out
echo $f
echo $f2
./plan $f $f2 $out >/dev/null
done
date2=$(date +%s%N | cut -b1-13)
diff=$(($date2-$date1))
#echo $date1
#echo $date2
echo "the duration is: $diff ms. for $traces traces"
#>/dev/null
