
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 15 16:29:45 CEST 2011
//----------------------------------------------------

package org.processmining.ltl2automaton.plugins.cup_parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int RELEASES = 17;
  public static final int AND = 7;
  public static final int OR = 8;
  public static final int RPAREN = 3;
  public static final int NOT = 6;
  public static final int WUNTIL = 16;
  public static final int TRUE = 4;
  public static final int FUTURE = 14;
  public static final int IMPLIES = 9;
  public static final int LPAREN = 2;
  public static final int ID = 19;
  public static final int WRELEASES = 18;
  public static final int EQUALS = 10;
  public static final int GLOBALLY = 13;
  public static final int EOF = 0;
  public static final int WNEXT = 12;
  public static final int FALSE = 5;
  public static final int error = 1;
  public static final int UNTIL = 15;
  public static final int NEXT = 11;
}

